# Generated by Django 5.2.4 on 2025-08-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contestant_voterecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contestant',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contestant',
            name='photoUrl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contestant',
            name='rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
